### ISSUE TITLE
Tokenizer does not handle encrypted environment variables

### ISSUE THREAD

**Issue by robpex** [openalm/Extension-UtilitiesPack#21] opened 2016-04-05 18:26 UTC
Tokenizer will not replace matched variables if the value is encrypted.

**Comment by pascalberger** [comment] 2016-04-05 19:20
This might be a duplicate of #20

**Comment by robpex** [comment] 2016-04-05 19:33
@pascalberger I understood that to be the "Secret" variables Microsoft documents, such as "Build.BuildNumber or BUILD_BUILDNUMBER". This is about the variables where you click the lock to encrypt them.  It's possible they're both not working for the same reason though?

**Comment by pascalberger** [comment] 2016-04-05 20:03
@robpex Not sure what exactly is meant in #20 (I understood it also as encrypted variables). Anyway it might be better to report this at https://github.com/Microsoft/vsts-agent, since this is something which currently cannot be handled in any custom task like the Tokenizer, since the task doesn't has access to the unencrypted value of the variable (Or maybe someone from MSFT can correct me if they know of any way).

**Comment by pviktor** [comment] 2016-04-06 08:16
I've fixed this problem and created a pull request. You can check it.

**Comment by harshil93** [comment] 2016-04-26 14:09
Waiting for the new sdk changes to get in.

**Comment by zsmorris** [comment] 2016-08-04 11:35
Why is this bug closed if it's not fixed?  Not being able to read encrypted variables makes this extension pretty much useless.  Is there duplicate bug issue somewhere else?

**Comment by zsmorris** [comment] 2016-08-04 11:39
What's the latest word on when this will be fixed?  Extension is pretty much useless without it.

**Comment by harshil93** [comment] 2016-08-31 09:57
@robpex @pascalberger @zsmorris 

If you pull in the latest source code and package it and use. You should be able to replace secret vars. Make sure you are using the new CoreCLR based agent with version >= **2.104.2**

**Comment by kvarley** [comment] 2016-10-18 13:34
I hate to pile on here but is there any plan for releasing this.  As near as I can tell, the code is already there but its not packaged as the primary task.

**Comment by harshil93** [comment] 2016-10-20 17:10
Released. See the 0.1.5 version VSIX package at the root of the github repo. 

It will be released to the marketplace very soon ( couple of days) 

@kvarley @robpex @pascalberger  @zsmorris 

You will be able to use secret variables only if you are on >2.104.2 agent version.

**Closed by harshil93** 2016-10-20 17:10 UTC
Labels: bug
